config/routes.rb
Rails.application.routes.draw do
  root "students#index"

  get "/students/academic-debt", to: "students#get_with_academic_debt"
  get "/students/successful-percentage", to: "students#get_successful_percentage"
  get "/students/successful-subjects", to: "students#get_successful_subjects"
  get "/students/groups-by-success", to: "students#get_groups_by_success"
  post "students", to: "students#create"

  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
  validates :surname, presence: true
  validates :group, presence: true, length: {maximum: 15}
  validates :geometry_score, presence: true, :inclusion => 2..5
  validates :algebra_score, presence: true, :inclusion => 2..5
  validates :informatics_score, presence: true, :inclusion => 2..5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      redirect_to @student
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    redirect_to root_path
  end

  def get_with_academic_debt
    @students = Student.where("geometry_score < 3 OR algebra_score < 3 OR informatics_score < 3")
  end

  def get_groups_by_success
    @groups = Student.distinct.pluck(:group)
    @groups_by_success = Hash.new
    # if @groups.empty
    #   return
    # end

    @groups.each do |group|
      students_count = Student.group(:group).count[group]
      successful_students = Student.select { |student|
        student.group == group &&
        student.geometry_score > 3 &&
        student.algebra_score > 3 &&
        student.informatics_score > 3
      }.count

      @groups_by_success[group] = successful_students * 100 / students_count
    end

    @groups_by_success = @groups_by_success.sort_by { |k, v| v}.reverse
  end

  def get_successful_percentage
    @total_count = Student.count

    if @total_count == 0
      @successful_percentage = 0
    else
      @successful_count = Student.where("geometry_score > 3 AND algebra_score > 3 AND informatics_score > 3").count
      @successful_percentage = @successful_count * 100 / @total_count
    end
  end

  def get_successful_subjects
    @scores_sum = Hash.new
    @scores_sum[t("model.subjects.geometry")] = Student.sum(:geometry_score)
    @scores_sum[t("model.subjects.algebra")] = Student.sum(:algebra_score)
    @scores_sum[t("model.subjects.informatics")] = Student.sum(:informatics_score)
    @scores_sum = @scores_sum.sort_by { |k, v| v}.reverse

    max_score_sum = @scores_sum[0][1]
    subj_array = []

    @scores_sum.each do |k, v|
      if v != max_score_sum || max_score_sum == 0
        break
      end

      subj_array.push(k)
    end

    @successful_subjects = !subj_array.empty? ? subj_array.join(", ") : t("message.empty_students")
  end

private
  def student_params
    params.require(:student).permit(:surname, :group, :geometry_score, :algebra_score, :informatics_score)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/Students.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lab7" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Lab7</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2022</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for @student, :html => { :class => "form-horizontal student" } do |f| %>

  <% if @student.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t("model.surname"), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :surname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:surname) %>
  </div>
  <div class="form-group">
    <%= f.label t("model.group"), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :group, :class => 'form-control' %>
    </div>
    <%=f.error_span(:group) %>
  </div>
  <div class="form-group">
    <%= f.label t("model.geometry_score"), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :geometry_score, :class => 'form-control' %>
    </div>
    <%=f.error_span(:geometry_score) %>
  </div>
  <div class="form-group">
    <%= f.label t("model.algebra_score"), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :algebra_score, :class => 'form-control' %>
    </div>
    <%=f.error_span(:algebra_score) %>
  </div>
  <div class="form-group">
    <%= f.label t("model.informatics_score"), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :informatics_score, :class => 'form-control' %>
    </div>
    <%=f.error_span(:informatics_score) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                students_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t 'helpers.links.edit', :default => [:'helpers.titles.edit', 'Edit %{model}'],
           :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/get_groups_by_success.html.erb
<h1><%=t("queries.groups_by_success") %></h1>

<%if @groups_by_success.empty? %>
  <h4><%=t("message.empty_groups") %></h4>
<% else %>
  <ul>
    <%@groups_by_success.each do |k, v| %>
      <li>
        <%= "#{k}: #{v}%" %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= link_to t('helpers.links.back'),
            students_path,
            :class => 'btn btn-primary' %>

app/views/students/get_successful_percentage.html.erb
<h1><%=t("queries.successful_percentage") %></h1>

<h4><%= @successful_percentage.to_s + '%'%></h4>

<%= link_to t('helpers.links.back'),
            students_path,
            :class => 'btn btn-primary' %>

app/views/students/get_successful_subjects.html.erb
<h1><%=t("queries.successful_subjects") %></h1>

<h4><%= @successful_subjects%></h4>

<%= link_to t("helpers.links.back"),
            students_path,
            :class => 'btn btn-primary' %>

app/views/students/get_with_academic_debt.html.erb
<h1><%=t("queries.students_with_academic_debt") %></h1>

<ul>
  <%@students.each do |student| %>
    <li>
      <%= link_to student.surname, student %>
    </li>
  <% end %>
</ul>

<%= link_to t('helpers.links.back'),
            students_path,
            :class => 'btn btn-primary' %>

app/views/students/index.html.erb
<%- model_class = Student -%>
<div class="page-header" style="margin-left: 50px">
  <h1><%=t 'title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t("model.id")%></th>
      <th><%= t("model.surname") %></th>
      <th><%= t("model.group") %></th>
      <th><%= t("model.geometry_score") %></th>
      <th><%= t("model.algebra_score") %></th>
      <th><%= t("model.informatics_score") %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.id, student_path(student) %></td>
        <td><%= student.surname %></td>
        <td><%= student.group %></td>
        <td><%= student.geometry_score %></td>
        <td><%= student.algebra_score %></td>
        <td><%= student.informatics_score %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      student_path(student), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_path(student), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_path(student),
                      :method => 'delete',
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>

<%= link_to t('queries.students_with_academic_debt'),
            "/students/academic-debt",
            :class => 'btn btn-primary' %>

<%= link_to t('queries.groups_by_success'),
            "/students/groups-by-success",
            :class => 'btn btn-primary' %>

<%= link_to t('queries.successful_percentage'),
            "/students/successful-percentage",
            :class => 'btn btn-primary' %>

<%= link_to t('queries.successful_subjects'),
            "/students/successful-subjects",
            :class => 'btn btn-primary' %>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t 'helpers.links.new', :default => [:'helpers.titles.new', 'New %{model}'],
           :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t 'model.student', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= t("model.surname") %>:</strong></dt>
  <dd><%= @student.surname %></dd>
  <dt><strong><%= t("model.group") %>:</strong></dt>
  <dd><%= @student.group %></dd>
  <dt><strong><%= t("model.geometry_score") %>:</strong></dt>
  <dd><%= @student.geometry_score %></dd>
  <dt><strong><%= t("model.algebra_score") %>:</strong></dt>
  <dd><%= @student.algebra_score %></dd>
  <dt><strong><%= t("model.informatics_score") %>:</strong></dt>
  <dd><%= @student.informatics_score %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>